# -*- coding: utf-8 -*-
"""EDA and Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7P9lWGRdEFjo-4ZYucyYi9vDKDSwTdW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

import tensorflow as tf
from tensorflow.keras import Model, Sequential, Input
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.metrics import precision_recall_curve, auc, roc_curve
from tensorflow.keras.layers import GaussianNoise

"""# Q1. Sourcing the Dataset"""

# Loading the dataset (on Google Colab)

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ACML Group Project/fraudTrain.csv')
df.head()

dftest = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ACML Group Project/fraudTest.csv')

"""# Q2. Data Exploration and Visualtion"""

df.describe()

df.info()

"""The data shows no missing values"""

# Check how amount is distributed

df['amt'].describe()

# Total # of fraudulent transactions

df.is_fraud.value_counts()

# Amount vs fraud

ax=sns.histplot(x='amt',data=df[df.amt<=1000],hue='is_fraud',stat='percent',multiple='dodge',common_norm=False,bins=25)
ax.set_ylabel('Percentage in Each Type')
ax.set_xlabel('Transaction Amount in USD')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])

"""The result is very interesting!
* Normal transactions tend to be around USD 200 or less
* Fraudulent transactions peak around USD 300 and then at the USD 800-1000 range. There are also a lot of small dollar value fradulent transactions
"""

# Spending category vs fraud

#calculate the percentage difference
a=df[df['is_fraud']==0]['category'].value_counts(normalize=True).to_frame().reset_index()
a.columns=['category','not fraud percentage']

b=df[df['is_fraud']==1]['category'].value_counts(normalize=True).to_frame().reset_index()
b.columns=['category','fraud percentage']
ab=a.merge(b,on='category')
ab['diff']=ab['fraud percentage']-ab['not fraud percentage']

ax=sns.barplot(y='category',x='diff',data=ab.sort_values('diff',ascending=False))
ax.set_xlabel('Percentage Difference')
ax.set_ylabel('Transaction Category')
plt.title('The Percentage Difference of Fraudulent over Non-Fraudulent Transations in Each Spending Category ')

"""Some spending categories see more fraud than others! Fraud tends to happen more often in 'Shopping_net', 'Grocery_pos', and 'Misc_net'"""

# Has age got anything to do with it?

import datetime as dt
df['age']=dt.date.today().year-pd.to_datetime(df['dob']).dt.year
dftest['age']=dt.date.today().year-pd.to_datetime(dftest['dob']).dt.year

ax=sns.kdeplot(x='age',data=df, hue='is_fraud', common_norm=False)
ax.set_xlabel('Credit Card Holder Age')
ax.set_ylabel('Density')
plt.xticks(np.arange(0,110,5))
plt.title('Age Distribution in Fraudulent vs Non-Fraudulent Transactions')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])

"""The age distribution is visibly different between 2 transaction types. In normal transactions, there are 2 peaks at the age of 37-38 and 49-50, while in fraudulent transactions, the age distribution is a little smoother and the second peak does include a wider age group from 50-65. This does suggest that older people are potentially more prone to fraud."""

# Time in the day vs Fraud

df['hour']=pd.to_datetime(df['trans_date_trans_time']).dt.hour
dftest['hour']=pd.to_datetime(dftest['trans_date_trans_time']).dt.hour

ax=sns.histplot(data=df, x="hour", hue="is_fraud", common_norm=False,stat='percent',multiple='dodge')
ax.set_ylabel('Percentage')
ax.set_xlabel('Time (Hour) in a Day')
plt.xticks(np.arange(0,24,1))
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])

"""Fraudulent payments happen disproportionately around midnight when most people are asleep."""

# Day of week vs Fraud

df['day']=pd.to_datetime(df['trans_date_trans_time']).dt.dayofweek
dftest['day']=pd.to_datetime(dftest['trans_date_trans_time']).dt.dayofweek

ax=sns.histplot(data=df, x="day", hue="is_fraud", common_norm=False,stat='percent',multiple='dodge')
ax.set_xticklabels(['',"Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
ax.set_ylabel('Percentage')
ax.set_xlabel('Day of Week')
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])

"""Fraudulent transactions tend to happen throughout the week"""

# Month vs Fraud

df['month']=pd.to_datetime(df['trans_date_trans_time']).dt.month
dftest['month']=pd.to_datetime(dftest['trans_date_trans_time']).dt.month

ax=sns.histplot(data=df, x="month", hue="is_fraud", common_norm=False,stat='percent',multiple='dodge')
ax.set_ylabel('Percentage')
ax.set_xlabel('Month')
plt.xticks(np.arange(1,13,1))
ax.set_xticklabels(["Jan","Feb","Mar","Apr","May","Jun","Jul",'Aug','Sep','Oct','Nov','Dec'])
plt.legend(title='Type', labels=['Fraud', 'Not Fraud'])

"""Fraudulent transactions are crowded between Jan and June"""

# Commented out IPython magic to ensure Python compatibility.
# Correlation Matrix

# %matplotlib inline
fig = plt.figure(figsize=(18,9))
# Select only numeric columns for correlation calculation
numeric_df = df.select_dtypes(include=np.number)
mask = np.triu(np.ones_like(numeric_df.corr()))
sns.heatmap(numeric_df.corr(), mask=mask, cmap='coolwarm', annot=True)

"""# Q3. Preprocessing"""

# Remove all Personally Identifiable Information (PII)

df = df.drop(columns=['Unnamed: 0','cc_num','first','last','trans_num','street', 'city','state','zip', 'dob'])
dftest = dftest.drop(columns=['Unnamed: 0','cc_num','first','last','trans_num','street', 'city','state','zip', 'dob'])
df

"""All columns with raw PII data are dropped.

---


"""

df.duplicated().sum()

"""The dataset shows zero duplicate entries."""

# Dropping original column

df = df.drop(columns= ['trans_date_trans_time'])

dftest = dftest.drop(columns= ['trans_date_trans_time'])

df

"""### Distance calculation
The dataset provides us with locations in terms of coordinates. In order to calculate the distance, we use the Haversine function to find the distance between the merchants and the location of the transactions




"""

# Distance calculation when given coordinates

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth's radius in kilometers

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dist_lat = lat2 - lat1
    dist_lon = lon2 - lon1

    a = np.sin(dist_lat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dist_lon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

df['distance_km'] = haversine(df['lat'], df['long'], df['merch_lat'], df['merch_long'])

dftest['distance_km'] = haversine(dftest['lat'], dftest['long'], dftest['merch_lat'], dftest['merch_long'])

df['distance_km'].head()

# Dropping original columns

df = df.drop(columns=['lat','long','merch_lat','merch_long'])

dftest = dftest.drop(columns=['lat','long','merch_lat','merch_long'])

df

"""## Feature Encoding and Scaling

### Target Encoding, One Hot Encoding and Scaling

Target encoding is applied to the "merchants" and the "jobs" columns. This allows to convert these columns into numerical values that the model can read. One hot encoding is applied to the "category","gender","day_of_week" to convert these columns into numerical data. Lastly we scale all the numerical data.
"""

# Applying target encoding on merchants

merchant_encoding = df.groupby('merchant')['is_fraud'].mean()
df['merchant_encoded'] = df['merchant'].map(merchant_encoding)

merchant_encoding = dftest.groupby('merchant')['is_fraud'].mean()
dftest['merchant_encoded'] = dftest['merchant'].map(merchant_encoding)

df

# Applying target encoding on jobs

job_encoding = df.groupby('job')['is_fraud'].mean()
df['job_encoding'] = df['job'].map(job_encoding)

job_encoding = dftest.groupby('job')['is_fraud'].mean()
dftest['job_encoding'] = dftest['job'].map(job_encoding)

df

# Dropping original columns

df = df.drop(columns =['merchant','job'])

dftest = dftest.drop(columns =['merchant','job'])

df

# Splitting the dataset into numerical and catergorical columns

numerical_cols = ['amt', 'distance_km', 'city_pop', 'unix_time','hour']

categorical_cols = ['category','gender','day']

# Isolate the columns to be standard scaled
scale_cols = [col for col in numerical_cols if col != 'amt']

# Apply the stateless log transformation to 'amt' on BOTH sets
df['amt_log'] = np.log1p(df['amt'])
dftest['amt_log'] = np.log1p(dftest['amt'])

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the training data (for the non-amt numerical columns)
df[scale_cols] = scaler.fit_transform(df[scale_cols])

# Transform the test data using the TRAIN parameters
dftest[scale_cols] = scaler.transform(dftest[scale_cols])

# Drop the original raw 'amt' column so your model only sees 'amt_log'
df = df.drop(columns=['amt'])
dftest = dftest.drop(columns=['amt'])

"""We scale down all other numerical columns such that mean is 0 and standard deviation is 1. For amt column, we use log transformation since there are a lot of small transactions (USD 5, 10, 15) and fewer large transaction (USD 100)"""

# Applying one hot encoding to categorical columns

df = pd.get_dummies(df, columns = categorical_cols)

dftest = pd.get_dummies(dftest, columns = categorical_cols)

df

"""## Input-Target split"""

# Split data into input and target

X_train_full = df.drop(columns=["is_fraud"], inplace=False)
Y_train_full = df["is_fraud"]

X_test = dftest.drop(columns=["is_fraud"], inplace=False)
Y_test = dftest["is_fraud"]

# Split the training data to create the Validation set (20%)

X_train, X_val, Y_train, Y_val = train_test_split(
    X_train_full,
    Y_train_full,
    test_size=0.20,
    random_state=42,
    stratify=Y_train_full
)

X_train_full.shape

X_train.shape

X_val.shape

X_test.shape